# Generated by Django 6.0.7 on 2026-07-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcriptions',
            options={'permissions': [('advanced', 'Advanced Perm'), ('pro', 'Pro Perm'), ('basic', 'Basic Perm'), ('basic_ai', 'Basic AI Perm')]},
        ),
    ]
